version: '3'
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://db/ -schemas=relational_meetup -user=postgres -password=changeme -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432