FROM node:latest
ARG gateway

WORKDIR ${gateway}
COPY ${gateway}/package*.json ./

RUN npm install
# If you are building your code for production

# RUN npm install --only=production
# Bundle app source
COPY ${gateway} ./
CMD [ "npm", "start" ]
EXPOSE 8000