version: '3.3'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ${GATEWAY}/Dockerfile
      args:
        gateway: ${GATEWAY}
    ports:
      - 80:8000
    environment:
      - messagebroker=amqp://messagebroker

  messagebroker:
    image: rabbitmq:3.7.3-management
    ports:
      - "15672:15672"
      - "5672:5672"