
version: "3.6"

services:
  eventstore:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit

  messagebroker-test:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"